apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: techtrends
        ports:
          - containerPort: {{ .Values.containerPorts.http.port }}
            protocol: {{ .Values.containerPorts.http.protocol }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPorts.http.port }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPorts.http.port }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
