apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  ports:
    - name: ports-4111-and-3111
      port: 4111
      protocol: TCP
      targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP
