namespace:
  name: sandbox
 
image:
  repository: sbodrero/techtrends
  tag: latest
  imagePullPolicy: IfNotPresent

containerPorts: 3111

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

service:
  type: ClusterIP
  port: 4111
  protocol: TCP
  targetPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111